### ISSUE TITLE
bug in use-standard-ellipsis

### ISSUE THREAD

**Issue by ZYSzys** [hustcc/lint-md#20]
貌似出了个小问题，第一个 error 没报错。。
![screen shot 2018-11-29 at 8 50 07 pm](https://user-images.githubusercontent.com/23313266/49222970-6377fb00-f418-11e8-8f5b-ea2772924a82.png)

是不是这里应该改成 3 ？
```js
27   const re = /\.{4,}/g; // 使用正则匹配
```

**Comment by hustcc** [comment]
是 4，英文的省略号三个点，还是可以用的！

**Comment by ZYSzys** [comment]
所以 test/use-standard-ellipsis 里的第一个 error 应该归到 good 里是吗

**Comment by hustcc** [comment]
是的。
