### ISSUE TITLE
期待增加 vscode 扩展

### ISSUE THREAD

**Issue by yhlben** [hustcc/lint-md#26]
期待增加 vscode 扩展支持，这样在编写阶段就能发现错误。

**Comment by hustcc** [comment]
周五有人给我提过他准备开发 vscode 插件了，开发完成后会更新 readme，尽请期待 (☉_☉)

**Comment by hustcc** [comment]
vscode 中搜索 `mdlint` 就可以安装了。

试用版阶段，有一些小 bug，可以尽管提出来。@HJIO 会负责维护和跟进。
