### ISSUE TITLE
【特性请求】支持所有 CJK 字符，乃至全角字符

### ISSUE THREAD

**Issue by TechQuery** [hustcc/lint-md#27]
不仅中英文间需要空格，所有 **CJK**、**全角字符**与**拼音文字**、**半角字符**之间都应该空一格

**Comment by hustcc** [comment]
拼音文字 是指什么？带音标的拼音吗？

如果在 unicode 中可以区分，增加这个是容易的！

**Comment by TechQuery** [comment]
我们汉语是象形文字，其它国家、地区现行的文字基本是拼音文字。

可以参考[这个正则](https://web-cell.tk/WebCell/file/source/utility/resource.js.html#lineNumber9)来区分全半角。

**Comment by hustcc** [comment]
我本周末加上，如果你有兴趣的话，可以 pr！

**Comment by hustcc** [comment]
不好意思，这段时间有些忙！考虑了一下，感觉对于对其他国家的 **CJK**、**全角字符**，不做强制要求吧。

目前先仅仅处理好中文的问题！感谢你的反馈~~~
