### ISSUE TITLE
增加规则

### ISSUE THREAD

**Issue by tsejx** [hustcc/lint-md#39]
[中文文案排版指北](https://mazhuang.org/wiki/chinese-copywriting-guidelines) 这里提到的几个规则感觉可以考虑添加到规则中。
* 数字与单位之间无需增加空格
* 全角标点与其他字符之间不加空格
* 不重复使用标点符号
* 专有名词使用正确的大小写
* 不要使用不地道的缩写

**Comment by hustcc** [comment]
专有名词，不地道的缩写，这些规则可能需要词库支持。
