### ISSUE TITLE
关于docker的问题

### ISSUE THREAD

**Issue by ontheway0101** [hustcc/lint-md#43]
```
docker run --rm -it yuque/lint-md lint-md README.md Document.md # 也可直接带其它参数
```

这条命令能够直接利用 docker 容器验证宿主机的 markdown 文件吗？

其中 `README.md Document.md` 是指什么？

**Comment by hustcc** [comment]
是指你需要 lint 的 markdown 文件。

**Comment by ontheway0101** [comment]
![Uploading Screenshot_20190716_225247.png…](demo)

不知道是不是我的理解有点问题，docker -ti 不是让容器执行 comand 命令吗？ 

容器无法识别到我宿主机上的 `readme.md` 文件吧

**Comment by hustcc** [comment]
@wi1dcard 顺便也一起看看这个问题~

**Comment by wi1dcard** [comment]
@ontheway0101 感谢关注。

你需要将宿主机的目录「挂载」到容器内部。可以使用 `-v` 参数，例如：

```
docker run --rm -it -p $(pwd):/docs yuque/lint-md lint-md /docs/foo.md
```

**Comment by ontheway0101** [comment]
已经可以使用了，多谢指导，工具很好用。
