### ISSUE TITLE
新版本 cli 无法修复

### ISSUE THREAD

**Issue by guanguans** [hustcc/lint-md#48]
## 新版本 cli 无法修复：

<img width="1028" alt="" src="https://user-images.githubusercontent.com/22309277/62780254-d8431f00-bae7-11e9-9225-adbf194f1c91.png">

**Comment by hustcc** [comment]
--fixed 参数加上，才是修复。

**Comment by guanguans** [comment]
@hustcc `--fixed` 也不行哦。

**Comment by hustcc** [comment]
自动修复命令（我前面写错了，是--fix）

```
lint-md README.md Document.md --fix
```

**Comment by guanguans** [comment]
@hustcc `no-long-code` 规则无法修复。

**Comment by hustcc** [comment]
是的，请看一下 readme。

这个规则是没法自动修复的，毕竟不同的语言，无法做到自动去换行。

**Comment by guanguans** [comment]
嗯，我通过配置解决了问题。感谢作者这么好的开源项目。

**Comment by hustcc** [comment]
😁
