### ISSUE TITLE
支持 --fix 参数

### ISSUE THREAD

**Issue by ZYSzys** [hustcc/lint-md#6]
要是能像 eslint 那样支持 --fix 参数就更好啦，能够自动修正一些简单的 lint errors(比如自动在中文与英文数字之间增加空格)。

**Comment by ZYSzys** [comment]
我尽力，不过对我来说还是有点难。😅

**Comment by hustcc** [comment]
@ZYSzys 已经增加了 --fix 的机制，虽然很挫，但是可以实现目标！
